# Generated by Django 4.1.2 on 2022-10-23 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d'),
        ),
    ]
